// Pure helpers for LiveKit voice/video E2EE shared-key distribution.
//
// The frame crypto itself is LiveKit's FrameCryptor (AES-GCM, run in the e2ee worker
// via ExternalE2EEKeyProvider — no hand-rolled media crypto). All we own is:
//   - generating the 32-byte room key,
//   - the convergence rule that makes every participant settle on ONE shared key
//     without a central coordinator, and
//   - (de)serializing the key into an envelope that rides the existing pairwise
//     Signal channel (encryptFor) so the server only ever relays ciphertext.
//
// Convergence model (gossip, no election round-trip): the canonical key for a call is
// the one generated by the participant with the lexicographically smallest user id.
// On join everyone announces their candidate; a peer holding a smaller-id key replies
// with it, and everyone adopts the smallest-id key they have seen. This settles in a
// round or two and self-heals when membership changes.

const KEY_BYTES = 32;
export const VOICE_ENVELOPE_TAG = "vk1";

export type VoiceKeyEnvelope = { v: typeof VOICE_ENVELOPE_TAG; k: string; s: string };

/** A fresh 32-byte room key (CSPRNG). LiveKit runs HKDF over it internally. */
export function generateRoomKey(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(KEY_BYTES));
}

const b64 = (u: Uint8Array): string => {
  let s = "";
  for (const x of u) s += String.fromCharCode(x);
  return btoa(s);
};
const unb64 = (s: string): Uint8Array => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

/** Serialize a room key + its originating user id for pairwise-encrypted relay. */
export function encodeVoiceEnvelope(key: Uint8Array, sourceId: string): string {
  return JSON.stringify({ v: VOICE_ENVELOPE_TAG, k: b64(key), s: sourceId } satisfies VoiceKeyEnvelope);
}

/** Parse a decrypted voice-key envelope, or null if it isn't one / is malformed. */
export function decodeVoiceEnvelope(json: string): { key: Uint8Array; sourceId: string } | null {
  let e: VoiceKeyEnvelope;
  try {
    e = JSON.parse(json) as VoiceKeyEnvelope;
  } catch {
    return null;
  }
  if (!e || e.v !== VOICE_ENVELOPE_TAG || typeof e.k !== "string" || typeof e.s !== "string") return null;
  let key: Uint8Array;
  try {
    key = unb64(e.k);
  } catch {
    return null;
  }
  if (key.length !== KEY_BYTES) return null;
  return { key, sourceId: e.s };
}

/** True when an incoming key should replace ours: we hold none, or it comes from a
 *  smaller-id source (the canonical winner). */
export function shouldAdopt(currentSourceId: string | null, incomingSourceId: string): boolean {
  return currentSourceId === null || incomingSourceId < currentSourceId;
}

/** True when an incoming candidate loses to ours, so we reply with ours to pull the
 *  sender toward the canonical key. */
export function shouldReplyWithOurs(ourSourceId: string, incomingSourceId: string): boolean {
  return incomingSourceId > ourSourceId;
}
